<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>default</LangVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="MessageBox.Avalonia" />
        <PackageReference Include="System.Composition" />
        <PackageReference Include="z440.atl.core" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Buran.Interfaces\Buran.Interfaces.csproj" />
      <ProjectReference Include="..\Buran.Localization\Buran.Localization.csproj" />
      <ProjectReference Include="..\Buran.SQLite\Buran.SQLite.csproj" />
      <ProjectReference Include="..\Buran.Types\Buran.Types.csproj" />
    </ItemGroup>

    <Import Project="..\PluginToHost.targets" />
</Project>
