<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" />
      <PackageReference Include="MessageBox.Avalonia" />
      <PackageReference Include="z440.atl.core" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Buran.Localization\Buran.Localization.csproj" />
    </ItemGroup>

</Project>
