<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
      <PackageReference Include="z440.atl.core" Version="7.16.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Buran.Localization\Buran.Localization.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="CommunityToolkit.Mvvm">
        <HintPath>..\..\..\..\..\..\..\..\home\alex\.nuget\packages\communitytoolkit.mvvm\8.4.2\lib\net8.0\CommunityToolkit.Mvvm.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
