<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets/Buran.ico</ApplicationIcon>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" PrivateAssets="All" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="HotAvalonia" PrivateAssets="All" />
        <PackageReference Include="System.Composition" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="ViewModels\ViewModelBase.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Buran.Interfaces\Buran.Interfaces.csproj" />
      <ProjectReference Include="..\Buran.Localization\Buran.Localization.csproj" />
      <ProjectReference Include="..\Buran.SQLite\Buran.SQLite.csproj" />
    </ItemGroup>

    <Import Project="..\Buran.Player\NativeLibVlc.targets" />
</Project>
